image: paschenh/openjdk_dockerce

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

services:
- name: docker:dind

stages:
- build
- deploy

gradle-build:
  stage: build
  script:
  - docker run --rm --name test_db --publish 5532:5432 --env POSTGRES_PASSWORD=test_db --env POSTGRES_USER=test_db --detach postgres:10.5
  - ./gradlew check build
  after_script:
  - docker rm -f test_db
  artifacts:
    paths:
    - build/libs
    expire_in: 1h

docker-deploy:
  stage: deploy
  only:
  - master
  image: docker:stable
  dependencies:
  - gradle-build
  script:
  - docker login --username "$CI_REGISTRY_USERNAME" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY_URL"
  - docker build --tag docker.iteratec.io/office-map/office-map .
  - docker push docker.iteratec.io/office-map/office-map
