version: '3'

services:
  database:
    image: postgres:10.5
    environment:
      POSTGRES_USER: officemap_dev
      POSTGRES_DB: officemap_dev
      POSTGRES_PASSWORD: somepassword
    ports:
    - 5432:5432
    volumes:
    - officemap-development-db-data:/var/lib/postgresql/data
  test-database:
    image: postgres:10.5
    environment:
      POSTGRES_USER: test_db
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: test_db
    ports:
    - 5532:5432

volumes:
  officemap-development-db-data: {}
